### ISSUE TITLE
Enhance STORYLINE (iss #65)

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#107]
Issue #65 was closed, this is the enhancement part of the closed issue:

When I create a storyline I include info about the wth (climate database) and soi (soil database) files in the ini files that are to be used.
Having no info in the story file about the climate and soil database when I select a storyline it has no effect on the climate/soil database select on GRID gui. If we would add this info to the story file it would easy to select the corresponding climate and soil database (similarly to the SITE when an ini file is selected, the embedded wth/soi/mgm files are also selected)

I put an enhanced story file on the server: 
home\fodor.nandor\AgroMo\data\input\storyline\cropland2.story

**Comment by hollorol** [comment]
Adding this new line is not necessary for the solution. I can read in the first ini fájl mentioned in the story file. Let's see, if it is slow or not. If it will be sufficient in speed we do not have to add this information.

**Comment by fodornandor** [comment]
True. You can retrieve it from the ini file

**Comment by hollorol** [comment]
Is it OK if I only do this for climate and soil (and postpone the algorithm selection part)?

**Comment by fodornandor** [comment]
Yes.

**Comment by hollorol** [comment]
This issue is fixed(4c07bc8e2d1645524c85b22d24817556f6a2e766), I find it fast. The branch is storyFill

**Comment by fodornandor** [comment]
How can I pull it in power shell? (for the first time)
