### ISSUE TITLE
MultiSite Calibration

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#108]
I believe the MonteCarlo method could be extended somehow like this:
Let's imagine that in the calibration folder there are multiple folders with all the necessary files for calibration.
In each iteration step, simulations are carried out with the files from all folders in the calibration folder.
There should be a file that stores the cumulated error of all simulations carried out in one iteration step (across the folders).

**Comment by fodornandor** [comment]
This is only for AgroMo 2.0

**Comment by hollorol** [comment]
This is good idea. There are 3 possibilities:

1. Do single site calibration on all sites, and see the likelihood uncertainity.
2. Define likelihood function (it can be the same for all) for all sites, and combine the likelihood results (your idea belongs here)
3. Do pareto for the multiple site.

I think we should provide option for all of them.

**Comment by fodornandor** [comment]
Let's talk about it (in person) I'd like to see an easy, straightforward method in the agromo (probably not providing options)

**Comment by fodornandor** [comment]
1)	a working directoryban kellenének almappák az  ini, soi, wth fájloknak (akkor lenne multisite, ha több ini-t találna az initialization almappában)
2)	az obs fájlban kell egy újabb adatoszlop amiben megadhatjuk, hogy az adat melyik cellára/site-ra vonatkozik
3)	vagy dupla monte carlo kellene ami először kiválaszt egy cellát aztán csinál egy site szintű paraméter optimalizációs lépést VAGY sima MC: adott random paraméter értékkészlettel lefut az összes cellára/site-ra; Az utóbbi szimpibb, lehet hogy lassabb de talán nem lesz olyan vészes… nyilván nem kell milliós MC-t csinálni ebben az esetben.

**Comment by fodornandor** [comment]
Based on the latest discussion:
1) run the model for a preselected subset of the 1104 cells (5-10 cells from each domain - NUTS3 region) 
2) run the model for every cell in the subset in each MC iteration step
3) aggregate simulation results and compare them to the observed data
NOTE: the function should work for one domain with one cell that is equivalent to the single site calibration

**Comment by fodornandor** [comment]
Done w extra: constrained
