### ISSUE TITLE
AgroMo 1.0

### ISSUE THREAD

**Issue by hollorol** [hollorol/AgroMo#112]
What should be done to AgroMo 1.0. Is it far?

**Comment by fodornandor** [comment]
We are two issues away (in priority order):
#107 
#105

**Comment by hollorol** [comment]
Issue 105 is solved! Please test it!

**Comment by fodornandor** [comment]
in which branch it is solved?

**Comment by hollorol** [comment]
It was solved with the help commit. It is in the devel. https://github.com/hollorol/AgroMo/commit/5558131eeafb986558f77a598e9bcf1a8680b185
