### ISSUE TITLE
FIX MS > HTML conversion

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#117]
Fix AgroMo HELP

**Comment by fodornandor** [comment]
Can you please fix this! I cannot make a new ditributable with a HELP we have at the moment.
What is needed:
1) white background
2) embedded images
3) if possible: Fira Sans font

**Comment by fodornandor** [comment]
This would be the most important one... badly needed for the distributable.

**Comment by hollorol** [comment]
It is done.

**Comment by fodornandor** [comment]
Szia Roli,

 

A develből frissítettem, de még mindig valami régi md jelenik meg… ez ok?

 

Nándi

**Comment by hollorol** [comment]
A mastert nézd, minden ott van

Üdv.:
Roli

**Comment by fodornandor** [comment]
OK, ez már sokkal jobb!

 

Ez a sor valamiért nem működött: <img="img/map_gui.png" style="width: 100%">

 

a kép helyett van ez.

 

Az nagy meló lenne hogy FiraSans fonttal legyen a html?

 

Nándi

**Comment by fodornandor** [comment]
done
