### ISSUE TITLE
Plot Export

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#119]
Export Plot data in an excel file.
Suggested location of the files: .\data\output\plot_data\

**Comment by hollorol** [comment]
Why? You can always export plots from plotly...

**Comment by fodornandor** [comment]
Export to an image file, yes. Is it possible to save the values as well? If yes, than we would not need the EXPORT button on the PLOT window.

**Comment by hollorol** [comment]
All of out data are in the database. There are plenty of utilities which can read sqlite database (even excel can connect to it..)

**Comment by fodornandor** [comment]
OK, then, get rid of the EXPORT button...

**Comment by hollorol** [comment]
We will get rid of the export button ( it is another issue)
