### ISSUE TITLE
Mask color picker does not work properly

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#120]
1) It's OK, if colors option is selected, but when you pick white black appears as a preview image
2) If interval is selected it does not matter which mask color you pick the map is created with white

**Comment by Erzsi86** [comment]
Sziasztok!

Melyik branch-en lehet foglalkozni ezzel a problémával?

Üdvözlettel:
Erzsi

Nándor Fodor <notifications@github.com> (időpont: 2020. okt. 24., Szo,
8:20) ezt írta:

**Comment by fodornandor** [comment]
I've created an Erzsi branch for you. 
Many thanks!

**Comment by fodornandor** [comment]
Solved! Great job Erzsi!
