### ISSUE TITLE
Calibration: No parameter set found

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#132]
More meaning full notification (error message) if no acceptable parameter set was found, e.g.: No parameter set found meeting all constraints

**Comment by hollorol** [comment]
It is done on devel

**Comment by fodornandor** [comment]
Many thanks!
-------- Eredeti üzenet --------Feladó: Roland Hollós ***@***.***> Dátum: 2021. 07. 05.  7:15  (GMT+01:00) Címzett: hollorol/AgroMo ***@***.***> Másolatot kap: Nándor Fodor ***@***.***>, Author ***@***.***> Tárgy: Re: [hollorol/AgroMo] Calibration: No parameter set found (#132) 
It is done on devel

**Comment by hollorol** [comment]
I think it is solved.

**Comment by fodornandor** [comment]
What should I expect? Is the message displayed on the GUI?

**Comment by hollorol** [comment]
Yes.
