### ISSUE TITLE
Calibration: display constrained variables

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#133]
Display the actual values of the constrained variables (perc50 of LAImax) for the calibrated (best) epc at the end of the calibration.

**Comment by hollorol** [comment]
Is it good if I put the partial results into a separate file?

**Comment by fodornandor** [comment]
This info could go into result.csv.E.g. to the beginning of the file.
-------- Eredeti üzenet --------Feladó: Roland Hollós ***@***.***> Dátum: 2021. 07. 05.  7:48  (GMT+01:00) Címzett: hollorol/AgroMo ***@***.***> Másolatot kap: Nándor Fodor ***@***.***>, Author ***@***.***> Tárgy: Re: [hollorol/AgroMo] Calibration: display constrained variables (#133) 
Is it good if I put the partial results into a separate file?

**Comment by hollorol** [comment]
It is solved now

**Comment by fodornandor** [comment]
Where is it pushed?

**Comment by hollorol** [comment]
RBBGCMuso
