### ISSUE TITLE
Calibration: merge consts.csv and th.txt

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#134]
Merge the consts.csv and th.txt file into constraints.csv (consts is missleading it could be an abbr. of constants) using the following syntax:
Threshold ratio of acceptance: 60
Expression,Min,Max
"SELECT(harvest_index, max)|median",0.45,0.55
"SELECT(proj_lai, max)|quantile(.,0.5)",2.5,4
"SELECT(flower_date, max)|quantile(.,0.5)",180,210

**Comment by hollorol** [comment]
Instead of the the mixed csv/ini syntax I would use simply json. It is done on devel.

```{json}
{
    "constraints": [

        {
            "Expression": "SELECT(harvest_index, max)|median",
            "Min": 0.25,
            "Max": 0.75
        },
        {
            "Expression": "SELECT(proj_lai, max)|quantile(.,0.5)",
            "Min": 1.5,
            "Max": 7
        },
        {
            "Expression": "SELECT(flower_date, max)|quantile(.,0.5)",
            "Min": 150,
            "Max": 250 
        }
    ],

    "treshold": 60
}

```

**Comment by fodornandor** [comment]
merge completed. constraints.json is required now containing all info
