### ISSUE TITLE
Plot Window Size

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#138]
Top-left is OK
Width is OK
Height should be increased having a similar vertical fill in front of the main frame than the horizontal fill.

![image](https://user-images.githubusercontent.com/50200865/135725334-539b9e03-93b6-4c9e-aec4-9b6fefdd2d2b.png)

**Comment by hollorol** [comment]
Although We can only a single variable, the tool was designed for multiple graphs. There is a little bottom margin between each graphs. This is the default behaviour, we do not have (yet) explicit control on this.

**Comment by fodornandor** [comment]
If I plot two graphs the frame height remains the same (see pic) I thought the plot frame dimensions are the 95 or 90% of the main frame and you can set it.

![image](https://user-images.githubusercontent.com/50200865/135808683-ba3f7eff-8f15-49e6-9c10-1d4890a8935e.png)

**Comment by hollorol** [comment]
I can set it, I've just given a reason of this behaviour. :)

**Comment by fodornandor** [comment]
Great! :) Since I like symmetry I prefer having the same margins at all sides of the plot frame

**Comment by fodornandor** [comment]
Please! Estimated time: 42 sec.

**Comment by hollorol** [comment]
Done

**Comment by fodornandor** [comment]
Indeed
