### ISSUE TITLE
T1-T2 values in queries

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#147]
Currently T1 and T2 dropdowns are filled up years between the dates defined in the selected storyline. If it is e.g. 2001-2020 and I'd like to make a query that uses the climate.db only, I cannot select time periods beyond 2020 since the highest value in the T2 dropdown is 2020. A creative solution would be needed to avoid this, e.g.: a (small) extra button (switch) next to the T2 dropdown that extends the values to 2100.

**Comment by fodornandor** [comment]
OR just simply fill up both dropdowns with values from 1951 to 2100 irrespective to the selected storyline.

**Comment by fodornandor** [comment]
fill up both dropdowns with values from 1951 to 2100 irrespective to the selected storyline.

**Comment by fodornandor** [comment]
Put a  "time frame": {min = 2001; max = 2100} section in the query template json files.

**Comment by hollorol** [comment]
I've fxed it.

**Comment by fodornandor** [comment]
indeed
