### ISSUE TITLE
Run grid cell in Site mode

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#149]
Flattening a grid cell input dataset can be done by using the controls already available in the Site form.
When the switch is slid to GRID position
1) the wider combobox (to the left) filled up with the file names (wo extension) in the .\AgroMo\data\input\storyline\ directory
2) cell id should be selected
3) clicking the (green) Refresh button makes the flattening (input file combos should be refreshed)

**Comment by fodornandor** [comment]
intuitive file name creation using the subfolder name selected from the .\AgroMo\data\input\initialization\grid\ folder:

[subfolder name]_[cell id]  

use this character chain as filename for all required input files: endpoint, ini, wth, soi, mgm, plt, hrv, frz, epc

Note some subfolder contains inis with names: cellid.ini others with names: cellid_1.ini (if exists '_1' should be omited)

**Comment by hollorol** [comment]
Can we close it?

**Comment by fodornandor** [comment]
Good job Roli! Thank you!
