### ISSUE TITLE
Grid run: unnecessary _1 ending of ini files

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#150]
This line in the story file:
1;1;2001;2100

refers to 1_1.ini file .
It would be much easier if it would refer to simply the 1.ini file. In this case the same set of ini files could be used for calibration and then for a grid run.

**Comment by hollorol** [comment]
Ok.

**Comment by hollorol** [comment]
Solved. Upgrading RBBGCMuso on constraints branch solves this issue

**Comment by fodornandor** [comment]
agreed: better fit to the logic of storylines to keep the _1 endings
