### ISSUE TITLE
SITE|GRID switch

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#161]
When this switch set to GRID the 'INI file:' label changes to 'GRIDDED DATASET:'.
Since it is coded it works only for English. Please modify the code to work if Hungarian is selected. For every other language 'GRIDDED DATASET:' is fine. For Hungarian please use 'RÁCSALAPÚ ADATBÁZISOK:'

Estimated time: 5 minutes

**Comment by hollorol** [comment]
I would suggest pictograms instead. These have fixed size and it can be language independent. Hover hint can provide meaning for all available languages.

**Comment by hollorol** [comment]
Ok, I missunderstood the issue. I'll do this.

**Comment by fodornandor** [comment]
:)
