### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#2]
The program freezes after choosing some non-active functionalities

Lefagyott az egész, nem tudtam  kilépni, visszaléptem a base oldalra de az exit gomb sem volt aktív. Szerintem próbáltam olyan gombokat használni ami nem volt aktív, lehet megzavarodott ettől.

**Comment by hollorol** [comment]
I can solve easily by improving the error handling. Can you help me to reproduce the behavior?

A probléma könnyen orvosolható egyszerű hibakezeléssel. Ehhez azonban tudnom kellene, hogy hol jelent meg a probléma. Tudnál segíteni a hiba reprodukálásában?

**Comment by hollorol** [comment]
It is not reproducible and have not been occured since, therefore I close this issue. I'll reopen if occures again.
