### ISSUE TITLE
Observation data on Graphs

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#22]
Link observation database to PLOT based on the settings defined by the two corresponding dropdown menus and the checkbox on the PLOT GUI. SQLite file is here (zipped)
[EXPERIMENT.zip](https://github.com/hollorol/AgroMo/files/4030059/EXPERIMENT.zip)

**Comment by hollorol** [comment]
It is solved now with [04bbf0e](https://github.com/hollorol/AgroMo/commit/04bbf0e930e89c5c5f33091e10b371e5afede8b6) commit on devel branch. You can test it. If it's working properly I will merge this into the master branch, otherwise I will reopen the issue.
