### ISSUE TITLE
Extreme check

### ISSUE THREAD

**Issue by SandorRenata** [hollorol/AgroMo#3]
How does AgroMo handle wrong fertilization input? 

Sziasztok! 
Meg lehetne nézni, hogy az AgroMo miként reagál (lefagy/kiszámolja/stb.) a mértékegység hibás managementre, pl. a műtrágya 500 kg/m2. Akkor hogy alakulna pl. a N lemosódás? 
Reni

**Comment by hollorol** [comment]
AgroMo does not handle this kind of errors yet, so the reaction is binary: run/not run. We are working on a lightweight solution which converts the BiomeBGC-MuSo 6.x error-codes  into messages.

Jelenleg sajnos az AgroMo még nem kezeli a hibás inputot kellően jól. Dolgozunk jelenleg egy megoldáson, ami a model által szolgáltatott hibakódokhoz megfelelő hibaüzeneteket rendel.
