### ISSUE TITLE
Observation Data on PLOT

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#33]
Use always **black** color for observed data (independent of the number of the plotted simulation results). In other words: use a 6th dataseries (graph, color: black) to plot/show the observed data.

**Comment by fodornandor** [comment]
Sorry for assigning it to you, but I think you can do it in a couple of minutes.

**Comment by hollorol** [comment]
This issue is solved with issue 79, where we changed the observed data representation.
