### ISSUE TITLE
PLOT: Soil Water Content

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#36]
Soil Water Content variables (for each layer) do not appear when 'water' is selected in the filter to menu. Problem with labeling in the central data table?

**Comment by hollorol** [comment]
Yes it is a problem with the central data table.

**Comment by fodornandor** [comment]
both soil and water are in the TAG field in the centraldata.json file
"TAG": "soil, water, water-profil" 
still, these variables do not appear when soil or water is selected as a filter
