### ISSUE TITLE
reinitialization BUG

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#45]
Simulation was made for maize, then the management file was set to NONE. Though there should not be any biomass production the LAI was extremely high and the plant height (and obviously the stem weight) did not started from zero… was way above zero right from the beginning of the simulation. See attached plot

**Comment by fodornandor** [comment]
![bug](https://user-images.githubusercontent.com/50200865/76604204-9ca18500-650e-11ea-8a49-b31f151197c0.png)

**Comment by hollorol** [comment]
This is solved in iss45_reinitialization branch.

**Comment by fodornandor** [comment]
solved
