### ISSUE TITLE
New category for plots

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#48]
In the centralData.json could we use a new TAG: "favorite". This tag would indicate those couple of favorite variables that are most frequently used by the user. Should the code be changed to implement this or it is enough to put this tag into the json file?

**Comment by fodornandor** [comment]
Hmmm. I tried… it is enough to put the new tag into the json file... works. Good job, Roli!

**Comment by fodornandor** [comment]
Could we put a button next to the filter to dropdown menu that would add the 'favorite' tag into the json file to the variables the are currently selected? In this way it would be so easy to make user defined selections of the variables.

**Comment by hollorol** [comment]
Thank you! :) We can do it.
