### ISSUE TITLE
Finalization of AgroMo folder structure

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#50]
NOTE: files are NOT located in the AgroMo\data\AgroMoData\ folder any more but in the AgroMo\data\ folder

Please rename:
1) AgroMo\app\R-Portable\library\AgroMo\tools TO AgroMo\app\R-Portable\library\AgroMo\tool
2) AgroMo\data\observation\ TO AgroMo\data\database\
3) AgroMo\data\templates\ TO AgroMo\data\template\

and change the code accordingly!

Please delete:
AgroMo\data\image\   (we don't use it)

Can we please store the content of the AgroMo\app\R-Portable\library\AgroMo\www\img\   folder  one level up in the the e:\AgroMo\app\R-Portable\library\AgroMo\img\  folder?

**Comment by fodornandor** [comment]
Please move the content of AgroMo\data\template\grid\ one level up TO AgroMo\data\template\

**Comment by fodornandor** [comment]
Do we need the AgroMo\data\output\queries\ folder and its content (sql files)?

**Comment by hollorol** [comment]
> Can we please store the content of the AgroMo\app\R-Portable\library\AgroMo\www\img\ folder one level up in the the e:\AgroMo\app\R-Portable\library\AgroMo\img\ folder?

We should not. The content of that directory in application layer, not user replacable. These images are the banners and other GUI elements.

> Please delete:
AgroMo\data\image\ (we don't use it)

Ok.

> NOTE: files are NOT located in the AgroMo\data\AgroMoData\ folder any more but in the AgroMo\data\ folder

Is it nwjs related?

**Comment by fodornandor** [comment]
I suggest storing the centralData.json file in the data folder AND delete only the img folder in the inst folder
