### ISSUE TITLE
Unable to delete simulation results (PLOT)

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#51]
It's a new issues. Wasn't a problem before. When a sim result (or more) selected and DELETE SELECTED clicked the Rscript.exe cmd window disappears and the program freezes (becomes grey). NOTE: I hade a Norton Security prompt before this issue started...

![bug_2020_03_24](https://user-images.githubusercontent.com/50200865/77400888-30474100-6dac-11ea-8e8c-5cce38b28d55.png)

**Comment by fodornandor** [comment]
I think its because of the sim result name that start with 01...

**Comment by fodornandor** [comment]
Yes, confirmed

**Comment by hollorol** [comment]
Thank you! Could you reopen the issue, because it is an issue for the sanitizer function.

**Comment by fodornandor** [comment]
Caused by the sanitizer function. Please solve!
