### ISSUE TITLE
Create folder for GRID runs

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#55]
AgroMo should create the following folders before start running a storyline (e.g. storyline1):

output\grid\storyline1
endpoint\grid\storyline1

**Comment by hollorol** [comment]
The first point is Ok, but the second (the endpoint) is not solvable, because it is a user input, unless we run the spinups (it would cost 50-100x the normal run in time)

**Comment by fodornandor** [comment]
Szia Roli, Nem a kiinduló endpointok mappájára gondolok, hanem a storyline futásakor keletkező endpointokat tartalamzó mappára. Annak uaz a neve mint az output mappában létrehozandónak. Nánd Küldte a Windows 10 Posta Feladó: Roland HollósElküldve: 2020. április 8., szerda 21:56Címzett: hollorol/AgroMoMásolatot kap: Nándor Fodor; AuthorTárgy: Re: [hollorol/AgroMo] Create folder for GRID runs (#55) The first point is Ok, but the second (the endpoint) is not solvable, because it is a user input, unless we run the spinups (it would cost 50-100x the normal run in time)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hollorol** [comment]
Got it
