### ISSUE TITLE
Something hides

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#56]
Some invisible object hides/covers a part of the QUERY ALIAS textbox in the GRID GUI.
From around 1/3 of the length from the left side. Move the mouse slowly from the left edge of the textbox to the right to see.

**Comment by hollorol** [comment]
I've also meet this issue, had tought that the issue relates to fonts

**Comment by fodornandor** [comment]
This invisible object hides/covers the first some one 7th part of the description textbox as well
