### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#63]
Please implement the following changes:
1) Trebuchet MS font > Fira Sans font
on the GRID form:
2) Locate the invisible object between the QUERY ALIAS and DESCRIPTION text boxes and cover some parts of them … and delet it.
3) increase the font size of the OUTPUT DATA TABLE, QUERY ALIAS and DESCRIPTION text boxes and change the font color to black
4) change the CLIMATE PROJECTION: label to CLIMATE DATABASE:
on the MAP form
5) try to move the two radiobuttons up with 1 px
on the SITE form:
6) move the date (day) labels to the left with 2 px
7) move the OUTPUT DATA TABLE: label up with 1 px

**Comment by hollorol** [comment]
This issue is almost solved, we have to install the font into inst/www/font folder, and load it in the first loadeded css. I'll do it.

**Comment by hollorol** [comment]
I solved this issue, it is in the devel branch
