### ISSUE TITLE
storyline

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#65]
When I create a storyline I include info about the wth (climate database) and soi (soil database) files in the ini files that are to be used.
Having no info in the story file about the climate and soil database when I select a storyline it has no effect on the climate/soil database select. I we would add this info to the story file it would easy to select the corresponding climate and soil database (similarly to the SITE when an ini file is selected, the embedded wth/soi/mgm files are also selected)

BUG: there is 'tmp' item in the CLIMATE DATABASE dropdown menu… despite the fact that I don't have this folder in the weather\grid folder

**Comment by hollorol** [comment]
This is two separate issue.
## The BUG.
- **Reason**: There is tmp subdirectory in your ERA folder. The function I use for list directories is at default recursive.
- **Solution**: You can use only flat weather directories or I can set recursivity off. 
## The enhancement
The solution is easy I'll do it.

**Comment by fodornandor** [comment]
BUG: No, no, I delete the tmp folder… it's totally unnecessary.

ENHANCEMENT: I'll will include the climate database and soil database in the story file that were selected when the storyline was created.

**Comment by fodornandor** [comment]
I'll send you a sample story file soon
