### ISSUE TITLE
Run on Server - Freeze when quit

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#67]
When I run AgroMo on the server and push the exit button, it freezes … or… does not close the window.

**Comment by hollorol** [comment]
Do not know how to solve this issue, because the server have to send a signal to the client to close a client app. Maybe nwjs has some possibilities.

**Comment by fodornandor** [comment]
Should I allow to run agromo in a browser (not in nwjs) when it is run on the server?   Küldte a Windows 10 Posta Feladó: Roland HollósElküldve: 2020. május 4., hétfő 21:20Címzett: hollorol/AgroMoMásolatot kap: Nándor Fodor; AuthorTárgy: Re: [hollorol/AgroMo] Run on Server - Freeze when quit (#67) Do not know how to solve this issue, because the server have to send a signal to the client to close a client app. Maybe nwjs has some possibilities.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hollorol** [comment]
Yes, that's a straightforward workaround (Alexander the Great way :) )

**Comment by fodornandor** [comment]
OK, I’ll do that.   Küldte a Windows 10 Posta Feladó: Roland HollósElküldve: 2020. május 4., hétfő 21:26Címzett: hollorol/AgroMoMásolatot kap: Nándor Fodor; AuthorTárgy: Re: [hollorol/AgroMo] Run on Server - Freeze when quit (#67) Yes, that's a straightforward workaround (Alexander the Great way :) )—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
