### ISSUE TITLE
REPORT: CSV - no, XLSX - yes

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#73]

**Comment by fodornandor** [comment]
+ use checkbox on the REPORT button:
if checked: show and save data
if not checked: only save data

**Comment by hollorol** [comment]
I cannot see the checkbox
![image](https://user-images.githubusercontent.com/15141218/88022718-12a6a000-cb30-11ea-9af7-c12320b11e6e.png)

**Comment by hollorol** [comment]
The problem is with firefox. It is sad, that we cannot use firefox anymore, just chrome(nwjs)

**Comment by hollorol** [comment]
This issue is solved with commit  efa67c783a6e1d2cf67ab30a0544876457210698 on issue 76 branch.
