### ISSUE TITLE
Data types in centralData.json

### ISSUE THREAD

**Issue by hollorol** [hollorol/AgroMo#81]
To solve issue 62, I need some help about the model outputs. We need an extra attribute, called: types. It should contain the datatype information for all variable.

**Comment by fodornandor** [comment]
Ha már beillesztünk egy VARTYPE oszlopot lenne szerinted értelme egy PRECISION oszlopnak, hogy mit hány tizedesre tároljunk?

**Comment by fodornandor** [comment]
TYPE column has been used for this. json file is attached. (extension should be changed to json)
[centralData.txt](https://github.com/hollorol/AgroMo/files/5050691/centralData.txt)
