### ISSUE TITLE
Grid run (annual outputs selected) halts when saving data into the DB 

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#92]

**Comment by fodornandor** [comment]
Ezt írja:
Warning: Error in <-: 'names' attribute [7] must be the same length as the vector [2]
  [No stack trace available]

**Comment by hollorol** [comment]
Megváltozó muso kódok centraldata problem

Üdv.:
Roli

**Comment by fodornandor** [comment]
Ezek elég régóta létező kimenetek, miért változott volna meg a kódjuk? Meg ha daily outputot választok akkor nincs gond

**Comment by fodornandor** [comment]
storyline file has to be syncronized with the ini file set
