### ISSUE TITLE
Run grid cell as if it was a site

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#94]
Rearrange SITE gui to make it possible. (some modifications to the code are also needed to avoid freezing)

**Comment by hollorol** [comment]
It can be done easily, if we don't want to use the shift and modifier part, just run the grid cell. We need two selector (story and cell) and thats all. Do we have space for that?

**Comment by hollorol** [comment]
Yes, we have, as I see there is more than enough space bellow the "shift in" part.

**Comment by fodornandor** [comment]
Thanks for the good news! No modifications in this case just run the model (select a stroyline and a grid cell) see attached GUI plan!
![site_gui2](https://user-images.githubusercontent.com/50200865/93003821-34297400-f542-11ea-9500-80164c9f47f9.png)

**Comment by hollorol** [comment]
It looks good, but I don't see the storyline selection part.

**Comment by fodornandor** [comment]
Because the switch is in SITE state. If you switch to GRID the GUI changes slightly
![site_gui2b](https://user-images.githubusercontent.com/50200865/93004179-f5e18400-f544-11ea-808e-2a39a388884f.png)

**Comment by hollorol** [comment]
I see now. :)

**Comment by fodornandor** [comment]
the upper left dropdown menu:
SITE mode: ini files from the initialization\site folder  (CELL id inactive)
GRID mode: subfolders in the initialization\grid folder  (CELL id active: files from the selected folder)

**Comment by fodornandor** [comment]
It would also solve the 'problem' of presenting grid run results (selected cells) on the PLOT GUI

**Comment by fodornandor** [comment]
Anna! Could you please add the new objects: label (CELL id:), dropdown menu and a switch (site <> grid) to the SITE GUI according to the above image?!

**Comment by hollorol** [comment]
The prototype is finished and is in the devel branch already.

**Comment by fodornandor** [comment]
yeah
