### ISSUE TITLE
Management: negative numbers in 'shift in' section

### ISSUE THREAD

**Issue by fodornandor** [hollorol/AgroMo#99]
Negative numbers entered in the shift in section (amount of fertilizer was tested) seems to be NOT working. Simulated yield does not change.

additionaly: addig more fertilizer (using + number) does not effect yield as expected

**Comment by fodornandor** [comment]
Files in the tmp folders does not change when shift in used... suspicious!

**Comment by hollorol** [comment]
I'll look at it. Is it in site mode or grid mode? It works only in site mode. Maybe that is the case

**Comment by fodornandor** [comment]
Site mode, sajnos

-------- Eredeti üzenet --------Feladó: Roland Hollós <notifications@github.com> Dátum: 2020. 09. 25.  19:53  (GMT+01:00) Címzett: hollorol/AgroMo <AgroMo@noreply.github.com> Másolatot kap: Nándor Fodor <fona1972@gmail.com>, Author <author@noreply.github.com> Tárgy: Re: [hollorol/AgroMo] Management: negative numbers in 'shift in' section (#99) 
I'll look at it. Is it in site mode or grid mode? It works only in site mode. Maybe that is the case

**Comment by hollorol** [comment]
i'll solve it! :)

**Comment by hollorol** [comment]
![ss](https://user-images.githubusercontent.com/15141218/94391972-4d900a00-0157-11eb-8aeb-8668e5b0bddc.png)
I cannot see any problem here... Everything works fine tmp is changing, everything reacts

**Comment by fodornandor** [comment]
Szia Roli,

 

Mindjárt elmennek a gyerekek a suliba és hívlak.

Addig is:

(semmi különbség a két futás között)

**Comment by hollorol** [comment]
Okok. Hármat futtattam, belezoomolva, mindegyik különbözik, sőt még a csatolt ábrán is.

**Comment by fodornandor** [comment]
A -350 és -640 –nel sincs semmi különbség… pedig az utóbbi gyakorlatialg már semmi trágyát nem kap (650 van a frz fájlban)
